stages:
  - build
  - test

# to cache both npm modules and Cypress binary we use environment variables
# to point at the folders we can list as paths in "cache" job settings
variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

# cache using branch name
# https://gitlab.com/help/ci/caching/index.md
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - node_modules

.install:
  before_script:
    - yarn install

.test:
  extends: .install
  stage: test
  script:
    - yarn test:unit --coverage
    - yarn test:e2e --headless

.build:
  extends: .install
  stage: build
  script:
    - yarn build

# Node LTS
test-node-lts:
  extends: .test
  image: cypress/base:10

build-node-lts:
  extends: .build
  image: cypress/base:10
