stages:
  - test
  - build

.install:
  before_script:
    - yarn install

.test:
  extends: .install
  stage: test
  script:
    - yarn test:unit
    - yarn test:e2e --headless

.build:
  extends: .install
  stage: build
  script:
    - yarn build

# Node Latest
test-node11:
  extends: .test
  image: node:11-alpine

build-node11:
  extends: .build
  image: node:11-alpine

# Node LTS
test-node10:
  extends: .test
  image: node:10-alpine

build-node10:
  extends: .build
  image: node:10-alpine
