name: CI

on: [push]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: yarn install
      - run: yarn build
        env:
          NODE_ENV: "production"
      - run: yarn lint
      - run: yarn typings

  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: yarn install
      - run: yarn test:unit --coverage
        env:
          CI: true
          NODE_ENV: "test"
      - run: yarn test:e2e --headless
        env:
          CI: true
          NODE_ENV: "test"
