name: CI

on: [push]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: "Build, Lint and Typings"
        run: |
          yarn install
          yarn build
          yarn lint
          yarn typings
        env:
          CI: true
          NODE_ENV: "production"

  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: "Test"
        env:
          CI: true
          NODE_ENV: "test"
        run: |
          yarn install
          yarn test:unit --coverage
          yarn test:e2e --headless
