name: Node CI

on: [push]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: install, build and lint
        run: |
          yarn install
          yarn build
          yarn lint
        env:
          CI: true
          NOD_ENV: "production"

  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: "Test"
        run: |
          yarn install
          yarn test:unit --coverage
          yarn test:e2e --headless
